name: pgformat-lint
on:
  push:

permissions:
  contents: read
  pull-requests: read

jobs:
  pgformat:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: pg_format check
        run: |
          diff=$(diff sqlc/queries.sql <(docker run --quiet --rm --volume "$(pwd)/sqlc/queries.sql:/work/queries.sql" backplane/pgformatter queries.sql))
          if [[ -n "$diff" ]]; then
            echo $diff
            exit 1
          fi
